name: ar_pictures
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  # Localization
  slang: ^3.31.1
  slang_flutter: ^3.31.0
  turkmen_localization_support: ^0.0.8
  flutter_localizations:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Navigation
  auto_route: ^9.2.1+1

  # Data
  dio: ^5.6.0
  directus: ^0.11.0
  shared_preferences: ^2.3.2
  drift: ^2.20.0
  drift_flutter: ^0.1.0
  equatable: ^2.0.5
  cached_network_image: ^3.4.1

  # State management
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

  # Service Locator
  get_it: ^7.7.0

  # Utility
  json_annotation: ^4.9.0
  collection: ^1.18.0
  flutter_archive: ^6.0.3
  talker_flutter: ^4.4.1
  flutter_dotenv: ^5.1.0

  # System
  path: ^1.9.0
  path_provider: ^2.1.4
  flutter_inappwebview: ^6.0.0
  permission_handler: ^11.3.1
  mobile_scanner: ^5.2.1

  # UI
  shimmer: ^3.0.0
  introduction_screen: ^3.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Code generation
  build_runner: ^2.4.12

  # Data
  drift_dev: ^2.20.0

  # Navigation
  auto_route_generator: ^9.0.0

  # State management
  mobx_codegen: ^2.6.1

  # Utility
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

  # Localization
  slang_build_runner: ^3.31.0

flutter:
  uses-material-design: true

  # assets
  assets:
    - assets/images/
    - assets/js/
    - assets/js/data/
    - .env

flutter_launcher_icons:
  image_path_android: "assets/images/app_logo.png"
  image_path_ios: "assets/images/app_logo.png"
  android: true 
  ios: true 
